/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Random;
import javax.swing.JOptionPane;
/**
 *
 * @author KAAVIASUDHAN
 */
public class InAdmin1AddAdmin extends javax.swing.JFrame {

    /**
     * Creates new form InAdmin1AddAdmin
     */
    public InAdmin1AddAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtadminid = new javax.swing.JTextField();
        txtadminname = new javax.swing.JTextField();
        txtDobadmin = new javax.swing.JTextField();
        tctphonenum = new javax.swing.JTextField();
        txtadminMail = new javax.swing.JTextField();
        txtUserAdmin = new javax.swing.JTextField();
        txtAdminPsd = new javax.swing.JTextField();
        btnCheck = new javax.swing.JButton();
        btnGene = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnSubmit = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtAdminAddress = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        JBtnMale = new javax.swing.JRadioButton();
        JBtnFemale = new javax.swing.JRadioButton();
        JBoxBloodgrp = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        JBoxTiming = new javax.swing.JComboBox<>();
        btnExit = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1660, 840));

        jLabel1.setFont(new java.awt.Font("Sitka Text", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("T K HOSPITAL SERVICE AND CENTER");

        jLabel2.setFont(new java.awt.Font("Sitka Text", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("T K ADMIN SESSION - ADD ADMIN");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        jLabel3.setText("Name of the Admin");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 98, 310, 45));

        jLabel5.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        jLabel5.setText("Blood group");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 224, 310, 45));

        jLabel6.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        jLabel6.setText("Mail");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 348, 310, 45));

        jLabel4.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        jLabel4.setText("DOB - Admin");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 161, 310, 45));

        jLabel7.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        jLabel7.setText("Phone number");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 287, 310, 43));

        jLabel8.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        jLabel8.setText("UserName (Login_Purpose)");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 411, 310, 45));

        jLabel9.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        jLabel9.setText("Password (Login_Purpose)");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 474, 310, 45));

        jLabel10.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        jLabel10.setText("Admin Id Number");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 35, 310, 45));

        txtadminid.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel1.add(txtadminid, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 35, 663, 45));

        txtadminname.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel1.add(txtadminname, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 98, 663, 45));

        txtDobadmin.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel1.add(txtDobadmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 161, 663, 45));

        tctphonenum.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel1.add(tctphonenum, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 287, 663, 43));

        txtadminMail.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel1.add(txtadminMail, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 348, 663, 45));

        txtUserAdmin.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel1.add(txtUserAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 411, 663, 45));

        txtAdminPsd.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel1.add(txtAdminPsd, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 474, 663, 45));

        btnCheck.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        btnCheck.setText("Check");
        btnCheck.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckActionPerformed(evt);
            }
        });
        jPanel1.add(btnCheck, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 290, 160, 40));

        btnGene.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        btnGene.setText("Generate");
        btnGene.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeneActionPerformed(evt);
            }
        });
        jPanel1.add(btnGene, new org.netbeans.lib.awtextra.AbsoluteConstraints(1163, 39, 95, 40));

        btnReset.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel1.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 165, 160, 40));

        btnSubmit.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        btnSubmit.setText("SUBMIT");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        jPanel1.add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 224, 160, 40));

        jLabel11.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        jLabel11.setText("Address");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 537, 310, 45));

        txtAdminAddress.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jPanel1.add(txtAdminAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 537, 630, 45));

        jButton1.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        jButton1.setText("+ Extension");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 348, 160, 45));

        jLabel12.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        jLabel12.setText("Blood Group");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 600, 310, 34));

        JBtnMale.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        JBtnMale.setText("Male");
        JBtnMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnMaleActionPerformed(evt);
            }
        });
        jPanel1.add(JBtnMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 600, 93, -1));

        JBtnFemale.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        JBtnFemale.setText("Female");
        JBtnFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBtnFemaleActionPerformed(evt);
            }
        });
        jPanel1.add(JBtnFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 600, 93, -1));

        JBoxBloodgrp.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        JBoxBloodgrp.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "O +ve", "O -ve", "A +ve", "A -ve", "B +ve", "B -ve", "AB +ve", "AB -ve" }));
        jPanel1.add(JBoxBloodgrp, new org.netbeans.lib.awtextra.AbsoluteConstraints(482, 224, 190, 40));

        jLabel13.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        jLabel13.setText("Shift Timing");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(761, 224, 160, 40));

        JBoxTiming.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        JBoxTiming.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Morning 06:00AM to 01:00PM", "Evening 01:30PM to 09:00PM", "Night     09:30PM to 05:30AM", "General  09:00AM to 05:30PM" }));
        jPanel1.add(JBoxTiming, new org.netbeans.lib.awtextra.AbsoluteConstraints(925, 224, -1, 40));

        btnExit.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        btnExit.setForeground(new java.awt.Color(255, 0, 0));
        btnExit.setText("X Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        btnBack.setFont(new java.awt.Font("Lucida Console", 1, 12)); // NOI18N
        btnBack.setText("< BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1614, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnBack)
                .addGap(160, 160, 160))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(110, 110, 110)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1310, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1500, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 143, Short.MAX_VALUE))
                .addGroup(layout.createSequentialGroup()
                    .addGap(1405, 1405, 1405)
                    .addComponent(btnExit)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 16, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(69, 69, 69)
                            .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(9, 9, 9)
                            .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGap(0, 726, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCheckActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckActionPerformed
        // TODO add your handling code here:
        try{
            int flag=0;
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/tk_hms","root","");
            String docid =txtadminid.getText();
            String s1="select did from doctor";
            Statement stmt= con.createStatement();
            ResultSet rs= stmt.executeQuery(s1);
            while(rs.next()){

                String n1=rs.getString(1);

                if(n1.equals(docid)){
                    flag=1;
                    JOptionPane.showMessageDialog(this, "Their is alredy register in this Id number:" + docid + " , Admin. Asign another number");
                    this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
                    InAdmin1 ad1 = new InAdmin1();
                    ad1.setVisible(true);
                }
            }
            if(flag==0){
                JOptionPane.showMessageDialog(this,"Their is no Admin Id in this number.");
            }
        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_btnCheckActionPerformed

    private void btnGeneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeneActionPerformed
        // TODO add your handling code here:

        Random num = new Random();
        String strMax = "10000";
        int max = Integer.parseInt(strMax);
        int x = num.nextInt(max) + 1;
        String strX = String.valueOf(x);
        txtadminid.setText(strX);
    }//GEN-LAST:event_btnGeneActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        txtUserAdmin.setText("");
        txtAdminPsd.setText("");
        txtadminid.setText("");
        txtadminname.setText("");
        txtDobadmin.setText("");
        tctphonenum.setText("");
        txtadminMail.setText("");
        JBoxBloodgrp.setSelectedItem("O +ve");
        txtAdminAddress.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
        
        String gen = null, blood;
        
        try{
            int flag=0;
            Class.forName("com.mysql.cj.jdbc.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/tk_hms","root","");

            /*Date and Time*/
            LocalDateTime myDateObj = LocalDateTime.now();
            DateTimeFormatter myFormatObj = DateTimeFormatter.ofPattern("dd-MM-yyyy HH:mm:ss");
            String formattedDate = myDateObj.format(myFormatObj);
            //System.out.println("After formatting: " + formattedDate);

            String adminid =txtadminid.getText();
            String adminname=txtadminname.getText();
            String dob=txtDobadmin.getText();
            String phone=tctphonenum.getText();
            String mail =txtadminMail.getText();
            String user = txtUserAdmin.getText();
            String psd = txtAdminPsd.getText();
            String address = txtAdminAddress.getText();
            String timing = (String) JBoxTiming.getSelectedItem();
            
            if(JBtnMale.isSelected()){
                gen = "M";
            } 
            else if(JBtnFemale.isSelected()){
                gen = "Male";                
            }
            
            //System.out.println(JBoxTiming.getSelectedItem());
            Statement stmt= con.createStatement();
            
            String sql = "insert into admin (regno,name,dob,gender,bloodgroup,timing,phone,address,mail,username,psd,applyon) values ("+adminid+",'"+adminname+"','"+dob+"','"+gen+"','"+JBoxBloodgrp.getSelectedItem()+"','"+timing+"','"+phone+"','"+address+"','"+mail+"','"+user+"','"+psd+"','"+formattedDate+"')";

            int reg=stmt.executeUpdate(sql);

            if(reg!=0){
                this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
                LoginAdmin la1 = new LoginAdmin();
                la1.setVisible(true);
            }
            JOptionPane.showMessageDialog(this, "Successfully Added Doctor Bio Details in the Doctor Table");
        }
        catch(Exception e){
            System.out.println(e);
            JOptionPane.showMessageDialog(this, "Error pls Checks" + e);
        }
    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String mailid = txtadminMail.getText();
        txtadminMail.setText(mailid+"@gamil.com");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void JBtnMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnMaleActionPerformed
        // TODO add your handling code here:
        JBtnMale.setSelected(true);
        JBtnFemale.setSelected(false);
    }//GEN-LAST:event_JBtnMaleActionPerformed

    private void JBtnFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBtnFemaleActionPerformed
        // TODO add your handling code here:
        JBtnMale.setSelected(false);
        JBtnFemale.setSelected(true);
    }//GEN-LAST:event_JBtnFemaleActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.dispatchEvent(new WindowEvent(this, WindowEvent.WINDOW_CLOSING));
        InAdmin1 ad1 = new InAdmin1();
        ad1.setVisible(true);
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InAdmin1AddAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InAdmin1AddAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InAdmin1AddAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InAdmin1AddAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InAdmin1AddAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> JBoxBloodgrp;
    private javax.swing.JComboBox<String> JBoxTiming;
    private javax.swing.JRadioButton JBtnFemale;
    private javax.swing.JRadioButton JBtnMale;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCheck;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnGene;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tctphonenum;
    private javax.swing.JTextField txtAdminAddress;
    private javax.swing.JTextField txtAdminPsd;
    private javax.swing.JTextField txtDobadmin;
    private javax.swing.JTextField txtUserAdmin;
    private javax.swing.JTextField txtadminMail;
    private javax.swing.JTextField txtadminid;
    private javax.swing.JTextField txtadminname;
    // End of variables declaration//GEN-END:variables
}
